{% set name = "apache-airflow-providers-odbc" %}
{% set version = "4.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_odbc-{{ version }}.tar.gz
  sha256: 0ec72d215c0ac738b02073749a4baa3085add8b92a5e3e64dc54b7173570b8f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.10.0
    - apache-airflow >=2.7.0
    - pyodbc >=5.0.0

test:
  imports:
    - airflow.providers.odbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-odbc for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/odbc/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-odbc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
